- name: Install python3
  apt:
    name: python3

- name: Install django
  pip:
    name: django
    executable: pip3

- name: Clone repo
  git:
    repo: "https://{{git_user | urlencode}}:{{git_pass | urlencode}}@github.com/RNagawidjaja/COMP90024_Assignment2.git"
    dest: "{{ install_location }}"
  become_user: ubuntu
  ignore_errors: yes

- name: Run django server
  shell: nohup python3 /home/ubuntu/assignment2/web_app/manage.py runserver {{ inventory_hostname }}:8000 &