- name: Install pip3
  apt:
    name: python3-pip

- name: Install tweepy
  pip:
    name: tweepy
    executable: pip3

- name: Install shapely
  pip:
    name: shapely
    executable: pip3

- name: Install couchdb
  pip:
    name: couchdb
    executable: pip3

- name: Install nltk
  pip:
    name: nltk
    executable: pip3

- name: Clone repo
  git:
    repo: "https://{{git_user | urlencode}}:{{git_pass | urlencode}}@github.com/RNagawidjaja/COMP90024_Assignment2.git"
    dest: "{{ install_location }}"
  become_user: ubuntu
  ignore_errors: yes
  
- name: Add no proxy ips
  lineinfile:
    path: "{{ install_location }}/twitter_crawler/config.py"
    regexp: '^DATABASE_IP'
    line: "DATABASE_IP = '{{ groups['dbservers'][0] }}'"

- name: Create service file
  template:
    src: twitter_stream.j2
    dest: /lib/systemd/system/twitter_stream.service
    mode: 0644

- name: Enable service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: twitter_stream