- hosts: localhost
  roles:
    - create_servers

- hosts: dbservers
  remote_user: ubuntu
  become: yes
  roles:
    - common
    - couch

- hosts: harvestservers
  remote_user: ubuntu
  become: yes
  roles:
    - common
    - harvester

- hosts: webservers
  remote_user: ubuntu
  become: yes
  roles:
    - common
    - webserver